
import "./globals.css";
import Footer from "@/components/footer";

export const metadata = {
  title: "Rudra Interior",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        {children}
      <Footer/>
      </body>
    </html>
  );
}
